service: sample-app
provider:
  name: aws
  #runtime: nodejs14.18
  stage: dev
  region: us-east-2
  memorySize: 128
functions:  
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
